import { useRef } from "react";
import { Upload, FileText, CheckCircle, Loader2, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { useEvidenceContext } from "@/contexts/EvidenceContext";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

export default function EvidenceAssessmentPage() {
  const {
    files,
    setFiles,
    isAssessing,
    setIsAssessing,
    assessmentStatus,
    setAssessmentStatus,
    reportData,
    setReportData,
    reportFilename,
    setReportFilename,
    clearEvidence,
  } = useEvidenceContext();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFiles(Array.from(e.target.files));
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    if (e.dataTransfer.files) {
      setFiles(Array.from(e.dataTransfer.files));
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDropzoneClick = () => {
    fileInputRef.current?.click();
  };

  const handleAssess = async () => {
    if (files.length === 0) return;
    
    // Get selected model from localStorage
    const selectedModel = localStorage.getItem("selectedModel");
    if (!selectedModel) {
      toast({
        title: "Model Required",
        description: "Please select an AI model in Settings before running an assessment.",
        variant: "destructive",
      });
      return;
    }

    setIsAssessing(true);
    setReportData(null);
    setAssessmentStatus("Uploading evidence files...");

    try {
      // Step 0: Validate uploaded evidences (dummy process)
      console.log("Step 0: Validating uploaded evidences...");
      setAssessmentStatus("Validating uploaded evidences...");
      await new Promise((resolve) => setTimeout(resolve, 5000));

      // Step 1: Upload files and assess evidence
      console.log("Step 1: Starting evidence assessment...");
      const formData = new FormData();
      formData.append("selected_model", selectedModel);
      formData.append("max_workers", "4");
      files.forEach((file) => {
        formData.append("evidence_files", file);
      });

      setAssessmentStatus("Assessing evidence against knowledge bases...");
      let assessResponse;
      try {
        assessResponse = await fetch(`${API_URL}/assess-evidence`, {
          method: "POST",
          body: formData,
        });
      } catch (fetchError) {
        throw new Error(`Cannot connect to API at ${API_URL}. Please ensure the external API is running.`);
      }

      if (!assessResponse.ok) {
        const errorData = await assessResponse.json().catch(() => ({}));
        console.error("Assessment API error:", errorData);
        throw new Error(errorData.detail || `Assessment failed with status ${assessResponse.status}`);
      }

      const assessResult = await assessResponse.json();
      console.log("Step 1 complete. Assessment result:", assessResult);
      
      if (!assessResult.success) {
        throw new Error(assessResult.error_details || "Assessment failed");
      }

      // Step 2: Generate summary report (optional - the workbook is already generated by assess-evidence)
      console.log("Step 2: Generating executive summary...");
      setAssessmentStatus("Generating executive summary...");
      
      let summaryResult = { success: true, executive_summary: "" };
      try {
        const summaryResponse = await fetch(`${API_URL}/generate-summary?selected_model=${encodeURIComponent(selectedModel)}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(assessResult.processing_summary?.assessment_results || []),
        });

        if (summaryResponse.ok) {
          summaryResult = await summaryResponse.json();
          console.log("Step 2 complete. Summary result:", summaryResult);
        } else {
          console.warn("Summary generation failed, continuing with workbook download...");
        }
      } catch (summaryError) {
        console.warn("Summary API error, continuing:", summaryError);
      }

      // Step 3: Download the report PDF if workbook_path is available
      console.log("Step 3: Preparing report for download...");
      if (assessResult.workbook_path) {
        setAssessmentStatus("Preparing report for download...");
        const filename = assessResult.workbook_path.split("/").pop() || "assessment-report.pdf";
        console.log("Downloading report:", filename);
        
        try {
          const downloadResponse = await fetch(`${API_URL}/download-report?filename=${encodeURIComponent(filename)}`);
          
          if (downloadResponse.ok) {
            const blob = await downloadResponse.blob();
            setReportData(blob);
            setReportFilename(filename);
            console.log("Report downloaded successfully");
          } else {
            console.warn("Download failed, creating JSON report instead");
            const blob = new Blob([JSON.stringify({
              assessment: assessResult,
              summary: summaryResult
            }, null, 2)], { type: "application/json" });
            setReportData(blob);
            setReportFilename("assessment-report.json");
          }
        } catch (downloadError) {
          console.warn("Download error:", downloadError);
          const blob = new Blob([JSON.stringify({
            assessment: assessResult,
            summary: summaryResult
          }, null, 2)], { type: "application/json" });
          setReportData(blob);
          setReportFilename("assessment-report.json");
        }
      } else {
        console.log("No workbook_path in response, creating JSON report");
        const blob = new Blob([JSON.stringify({
          assessment: assessResult,
          summary: summaryResult
        }, null, 2)], { type: "application/json" });
        setReportData(blob);
        setReportFilename("assessment-report.json");
      }

      setAssessmentStatus("Assessment complete!");
      toast({
        title: "Assessment Complete",
        description: "Your evidence has been assessed. You can now download the report.",
      });
    } catch (error) {
      console.error("Assessment error:", error);
      setAssessmentStatus("");
      toast({
        title: "Assessment Failed",
        description: error instanceof Error ? error.message : "An error occurred during assessment",
        variant: "destructive",
      });
    } finally {
      setIsAssessing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!reportData) return;
    const url = URL.createObjectURL(reportData);
    const a = document.createElement("a");
    a.href = url;
    a.download = reportFilename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full overflow-auto">
      <div className="container mx-auto p-6 max-w-4xl">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Upload Evidence Files
            </CardTitle>
            <CardDescription>
              Upload your evidence files for AI-powered assessment and analysis
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div
              className="border-2 border-dashed rounded-md p-8 text-center cursor-pointer hover-elevate"
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onClick={handleDropzoneClick}
              data-testid="dropzone-upload"
            >
              <input
                ref={fileInputRef}
                type="file"
                multiple
                className="hidden"
                onChange={handleFileChange}
                accept=".pdf,.doc,.docx,.txt,.xlsx,.xls,.csv"
                data-testid="input-file"
              />
              <Upload className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
              <p className="text-lg font-medium">
                Drag and drop files here, or click to browse
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                Supports PDF, Word, Excel, CSV, and text files
              </p>
            </div>

            {files.length > 0 && (
              <div className="space-y-3">
                <h3 className="font-medium">Selected Files ({files.length})</h3>
                <div className="space-y-2">
                  {files.map((file, index) => (
                    <div
                      key={index}
                      className="flex items-center gap-3 p-3 bg-muted/50 rounded-md"
                      data-testid={`file-item-${index}`}
                    >
                      <FileText className="h-5 w-5 text-muted-foreground" />
                      <span className="flex-1 truncate" data-testid={`text-filename-${index}`}>{file.name}</span>
                      <span className="text-sm text-muted-foreground" data-testid={`text-filesize-${index}`}>
                        {(file.size / 1024).toFixed(1)} KB
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {assessmentStatus && (
              <div className="p-3 bg-muted/50 rounded-md" data-testid="status-assessment">
                <p className="text-sm flex items-center gap-2">
                  {isAssessing && <Loader2 className="h-4 w-4 animate-spin" />}
                  {!isAssessing && reportData && <CheckCircle className="h-4 w-4 text-green-500" />}
                  {assessmentStatus}
                </p>
              </div>
            )}

            <div className="flex gap-3">
              <Button
                onClick={handleAssess}
                disabled={files.length === 0 || isAssessing}
                className="flex-1"
                data-testid="button-assess"
              >
                {isAssessing ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Assessing...
                  </>
                ) : (
                  <>
                    <CheckCircle className="h-4 w-4 mr-2" />
                    Start Assessment
                  </>
                )}
              </Button>
              {reportData && (
                <Button
                  onClick={handleDownloadReport}
                  variant="default"
                  className="bg-green-600 hover:bg-green-700"
                  data-testid="button-download-report"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download Report
                </Button>
              )}
              <Button
                variant="outline"
                onClick={clearEvidence}
                disabled={files.length === 0 && !reportData}
                data-testid="button-clear-files"
              >
                Clear
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
